GET https://scripture-app-api.vercel.app/scriptures/

###

PATCH http://localhost:3000/users/notify/68d2cb14bca51054c4bd937f
Content-Type: application/json

{
    "message": "notifications testing"
}

###
POST https://scripture-app-api.vercel.app/users/
Content-Type: application/json

{
    "email": "116superstm@gmail.com",
    "password": "Admin123!"
}