GET https://scripture-app-api.vercel.app/scriptures/

###

POST  http://localhost:3000/scriptures/filter/1/50
Content-Type: application/json

{"scripture": "Genesis", "verse": "", "category": ""}

###
POST https://scripture-app-api.vercel.app/users/
Content-Type: application/json

{
    "email": "116superstm@gmail.com",
    "password": "Admin123!"
}