GET http://localhost:3000/scriptures/

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "firstname": "Admin",
    "lastname": "super",
    "phone": "0987654321",
    "email": "116superstm@gmail.com",
    "password": "Admin123!"
}

###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "email": "116superstm@gmail.com",
    "password": "Admin123!"
}